### ISSUE TITLE
Error: Request failed with status code 403

### ISSUE THREAD

**Issue by aravindsomaraj** [joshcai/leetcode-sync#57] opened 2024-03-18 18:58 UTC
The github action used to work without issues until a while ago, where I keep getting this error, even after updating my `LEETCODE_SESSION` token.

I ran it as both a workflow on Github several times, as well as locally on my pc. I'm getting the same error both ways.

```
(node:41200) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[Mon, 18 Mar 2024 18:47:34 GMT] Getting submission from LeetCode, offset 0
[Mon, 18 Mar 2024 18:47:34 GMT] Error: Request failed with status code 403
    at createError (/home/leetcode-sync/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/leetcode-sync/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/leetcode-sync/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Has anyone else been facing this issue?

**Comment by 5ecret99** [comment] 2024-03-18 21:15
https://github.com/joshcai/leetcode-sync/issues/56

**Comment by joshcai** [comment] 2024-03-25 04:41
Thanks for the bug report @aravindsomaraj ! I will close this as this is a duplicate of #56 as @5ecret99, please follow along there (I have commit to fix and it's working for me, but will see if anyone has any issues in #56).

**Closed by joshcai** 2024-03-25 04:41 UTC
