### ISSUE TITLE
Error getting info for submission

### ISSUE THREAD

**Issue by phillip055** [joshcai/leetcode-sync#58] opened 2024-04-07 07:19 UTC
```
TypeError: Cannot read properties of null (reading 'toFixed')
    at getInfo (/home/runner/work/_actions/joshcai/leetcode-sync/v1.6/dist/index.js:14581:89)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getInfo (/home/runner/work/_actions/joshcai/leetcode-sync/v1.6/dist/index.js:14609:10)
    at async Object.sync (/home/runner/work/_actions/joshcai/leetcode-sync/v1.6/dist/index.js:14902:18)
    at async main (/home/runner/work/_actions/joshcai/leetcode-sync/v1.6/dist/index.js:19564:3)
Error: TypeError: Cannot read properties of null (reading 'toFixed')
```

Quick debug it's get getinfo function, probably that the percentiles are of a different type than expected

**Comment by sriharshamadala** [comment] 2024-05-26 16:42
I am getting the same error.
```
[Sun, 26 May 2024 16:36:21 GMT] Syncing 216 submissions...
[Sun, 26 May 2024 16:36:21 GMT] Error fetching submission info, retrying in 1 seconds...
[Sun, 26 May 2024 16:36:23 GMT] Error fetching submission info, retrying in 3 seconds...
[Sun, 26 May 2024 16:36:26 GMT] Error fetching submission info, retrying in 9 seconds...
[Sun, 26 May 2024 16:36:35 GMT] Error fetching submission info, retrying in 27 seconds...
[Sun, 26 May 2024 16:37:02 GMT] Error fetching submission info, retrying in 81 seconds...
[Sun, 26 May 2024 16:38:23 GMT] TypeError: Cannot read properties of null (reading 'toFixed')
    at getInfo (/home/runner/work/_actions/joshcai/leetcode-sync/v1.6/dist/index.js:14581:89)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getInfo (/home/runner/work/_actions/joshcai/leetcode-sync/v1.6/dist/index.js:14609:10)
    at async Object.sync (/home/runner/work/_actions/joshcai/leetcode-sync/v1.6/dist/index.js:14902:18)
    at async main (/home/runner/work/_actions/joshcai/leetcode-sync/v1.6/dist/index.js:195[64](https://github.com/sriharshamadala/Leetcode/actions/runs/9244732283/job/25430371657#step:2:65):3)
Error: TypeError: Cannot read properties of null (reading 'toFixed')
```

**Comment by joshcai** [comment] 2024-06-26 15:47
Thanks @jaspinderkohli - I made a new release with the change and will close this now. If the issue is still present for anyone, please re-open.

**Closed by joshcai** 2024-06-26 15:47 UTC
